name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      # Install AWS CLI
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-cli@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Zip Lambda Code
      - name: Zip Lambda Code
        run: |
          zip -j lambda.zip lambda/app.py
          mv lambda.zip terraform/

      # Initialize Terraform
      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      # Validate Terraform
      - name: Terraform Validate
        working-directory: terraform/
        run: terraform validate

      # Apply Terraform
      - name: Terraform Apply
        working-directory: terraform/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: terraform apply -auto-approve
